
CREATE TABLE Students(
[StudentID] INT PRIMARY KEY IDENTITY,
[Name]		NVARCHAR(20) NOT NULL)

GO

CREATE TABLE Exams(
[ExamID]    INT PRIMARY KEY IDENTITY(101, 1),
[Name]		NVARCHAR(20) NOT NULL)

GO

CREATE TABLE StudentsExams(
[StudentID] INT FOREIGN KEY REFERENCES Students([StudentID]) NOT NULL,
[ExamID]	INT FOREIGN KEY REFERENCES Exams([ExamID]) NOT NULL,
PRIMARY KEY(StudentID, ExamID))