
CREATE DATABASE OnlineStore

GO

USE OnlineStore

GO

CREATE TABLE Cities(
CityID  	INT PRIMARY KEY NOT NULL,
CityName	VARCHAR(50)		NOT NULL)

GO

CREATE TABLE Customers(
CustomerID	  INT PRIMARY KEY NOT NULL,
CustomerName  VARCHAR(50)	  NOT NULL,
Birthday	  DATETIME2		  NOT NULL,
CityID		  INT FOREIGN KEY REFERENCES Cities(CityID) NOT NULL)

GO

CREATE TABLE Orders(
OrderID		INT PRIMARY KEY NOT NULL,
CustomerID	INT FOREIGN KEY REFERENCES Customers(CustomerID) NOT NULL) 

GO

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY NOT NULL,
TypeName   VARCHAR(50) NOT NULL)

GO

CREATE TABLE Items(
ItemID		INT PRIMARY KEY NOT NULL,
ItemName	VARCHAR(50)		NOT NULL,
ItemTypeID	INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID) NOT NULL)

GO

CREATE TABLE OrderItems(
OrderID		INT FOREIGN KEY REFERENCES Orders(OrderID) NOT NULL,
ItemID		INT FOREIGN KEY REFERENCES Items(ItemID) NOT NULL,
PRIMARY KEY (OrderID, ItemID))
